---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-base-file"
spec:
  title: Member Base File
  connectionType: file
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: ./src/main/resources/data/members_100_v14.csv
    - name: csv/header
      value: true
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-feedback-file"
spec:
  title: Member Feedback File
  connectionType: file
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: ./src/main/resources/data/feedback_100_v14.csv
    - name: csv/header
      value: true
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-flu-risk-file"
spec:
  title: Member Flu File
  connectionType: file
  contentType: parquet
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: ./src/main/resources/data/member_flu_risk_100_v14.parquet
    - name: secretParam
      value: "#SECURE.secret-key"
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-joined-file"
spec:
  title: Member Joined File
  connectionType: file
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
    - name: csv/header
      value: true
    - name: uri
      value: ./build/tmp/test-data/joined_v14.csv