apiVersion: cognitivescale.io/v1
kind: ProfileSchema
metadata:
  name: member-profile
spec:
  names:
    title: Member
    singular: member
    plural: members
    categories:
      - healthcare
      - customer

  # Source used in this profile schema
  primarySource:
    name: member-base-ds
    profileKey: member_id
    profileGroup: Demographics
    timestamp:
      auto: true
    attributes:
      - state_code
      - city
      - state
      - zip_code
      - gender
      - email
      - segment
      - member_health_plan
      - is_PCP_auto_assigned
      - pcp_tax_id
      - address
      - phone
      - do_not_call
      - channel_pref
      - age
      - last_flu_shot_date
      - pcp_name
      - pcp_address

  # List of sources to join into this profile schema
  joins:
    - name: member-flu-risk-file-ds
      join:
        primarySourceColumn: member_id  # column in the primary source to join on
        joinSourceColumn: member_id     # column in the join source to join on
      profileGroup: Inferences
      timestamp:
        field: date
        format: yyyy-MM-dd # Default is MM-dd-yyyy HH:mm:ss.SSS
      attributes:
        - flu_risk_score

  attributes:
    - name: avg_flu_risk
      profileGroup: Inferences
      source:
        name: member-flu-risk-file-ds
      type: custom
      expression: flu_risk_score.mean()
      window: DAILY

    - name: flu_risk_1_pct
      profileGroup: Inferences
      source:
        name: member-flu-risk-file-ds
      type: custom
      expression: flu_risk_score.percentile(0.99)
      window: DAILY

    - name: is_flu_risk_1_pct
      profileGroup: Inferences
      type: custom
      expression: flu_risk_score.gte(flu_risk_1_pct)

    - name: has_phone_number
      profileGroup: Demographics
      source:
        name: member-base-ds
      type: custom
      expression: phone.notEqual('').or(phone.notEqual(null))

    - name: age_group
      profileGroup: Demographics
      source:
        name: member-base-ds
      type: bucket
      buckets:
        - name: Under 30
          filter: age.lt(30)
        - name: 30-45
          filter: age.gte(30).and(age.lt(45))
        - name: 45-55
          filter: age.gte(45).and(age.lt(55))
        - name: 55-65
          filter: age.gte(55).and(age.lt(65))
        - name: 65+
          filter: age.gte(65)
---
apiVersion: cognitivescale.io/v1
kind: ProfileSchema
metadata:
  name: member-profile-no-job
spec:
  names:
    title: Member
    singular: member
    plural: members
    categories:
      - healthcare
      - customer

  # Source used in this profile schema
  primarySource:
    name: member-base-ds
    profileKey: member_id
    profileGroup: Demographics
    timestamp:
      auto: true
    attributes:
      - state_code
      - city
      - state
      - zip_code
      - gender
      - email
      - segment
      - member_health_plan
      - is_PCP_auto_assigned
      - pcp_tax_id
      - address
      - phone
      - do_not_call
      - channel_pref
      - age
      - last_flu_shot_date
      - pcp_name
      - pcp_address

  # List of sources to join into this profile schema
  joins:
    - name: member-flu-risk-file-ds
      join:
        primarySourceColumn: member_id  # column in the primary source to join on
        joinSourceColumn: member_id     # column in the join source to join on
      profileGroup: Inferences
      timestamp:
        field: date
        format: yyyy-MM-dd # Default is MM-dd-yyyy HH:mm:ss.SSS
      attributes:
        - flu_risk_score

  attributes:
    - name: avg_flu_risk
      profileGroup: Inferences
      source:
        name: member-flu-risk-file-ds
      type: custom
      expression: flu_risk_score.mean()
      window: DAILY

    - name: flu_risk_1_pct
      profileGroup: Inferences
      source:
        name: member-flu-risk-file-ds
      type: custom
      expression: flu_risk_score.percentile(0.99)
      window: DAILY

    - name: is_flu_risk_1_pct
      profileGroup: Inferences
      type: custom
      expression: flu_risk_score.gte(flu_risk_1_pct)

    - name: has_phone_number
      profileGroup: Demographics
      source:
        name: member-base-ds
      type: custom
      expression: phone.notEqual('').or(phone.notEqual(null))

    - name: age_group
      profileGroup: Demographics
      source:
        name: member-base-ds
      type: bucket
      buckets:
        - name: Under 30
          filter: age.lt(30)
        - name: 30-45
          filter: age.gte(30).and(age.lt(45))
        - name: 45-55
          filter: age.gte(45).and(age.lt(55))
        - name: 55-65
          filter: age.gte(55).and(age.lt(65))
        - name: 65+
          filter: age.gte(65)
