apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cortex-compute
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumeclaim"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: cortex-compute
subjects:
- kind: ServiceAccount
  name: default
  namespace: cortex-compute
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
