class Constant:
    SEND_FLU_SHOT_SYDNEYCARE_NOTIFICATION = "1"
    SEND_FLU_SHOT_NURSELINE_NOTIFICATION = "2"
    SEND_FLU_SHOT_SYDNEYCARE_APPOINTMENT_NOTIFICATION = "3"
    SEND_VIRTUAL_CARE_NURSE_NOTIFICATION = "4"
    SEND_SYDNEYCARE_CHATBOT_ENGAGE_NOTIFICATION = "5"
    UPDATE_PHONE_NUMBER = "6"
    FLU_SHOT_CAMPAIGN_TYPE = "flu_shot"