FROM c12e/cortex-amp-spark-submit:latest-develop-ubi8

USER root

COPY src/ src/
RUN pip install -r src/main/python/requirements.txt

ENV JAVA_HOME /usr/local/openjdk-11
ENV SPARK_HOME /opt/spark
ENV ENVOY_ADMIN_API=http://localhost:15000
ENV ISTIO_QUIT_API=http://localhost:15020

WORKDIR /opt/spark/work-dir
RUN chmod g+w /opt/spark/work-dir
RUN chmod a+x /opt/decom.sh

ARG spark_uid=185
USER ${spark_uid}

ENTRYPOINT ["/bin/scuttle", "/opt/entrypoint.sh"]