apiVersion: "fabric.cognitivescale.com/v1"
kind: "Connection"
metadata:
  "name": "member-feedback"
spec:
  title: "member-feedback"
  description: ""
  connectionType: "s3"
  contentType: "parquet"
  allowRead: true
  allowWrite: false
  params:
  - name: "uri"
    value: "s3a://ol-test-data/member_feedback_v15.parquet"
  - name: "publicKey"
    value: "AKIAY4JSNX4D2OMJE3UN"
  - name: "secretKey"
    value: "#SECURE.awssecret"
  - name: "s3Endpoint"
    value: "http://s3.us-east-1.amazonaws.com"