apiVersion: "fabric.cognitivescale.com/v1"
kind: "ProfileSchema"
metadata:
  "name": "member-profile"
spec:
  names:
    title: "member-profile"
    singular: ""
    plural: ""
    categories: []
  primarySource:
    name: "member-base"
    profileKey: "member_id"
    profileGroup: "Demographics"
    timestamp:
      auto: true
      field: null
      format: null
      fixed: null
    attributes:
    - "pcp_name"
    - "state_code"
    - "city"
    - "state"
    - "zip_code"
    - "gender"
    - "segment"
    - "member_health_plan"
    - "is_PCP_auto_assigned"
    - "pcp_tax_id"
    - "phone"
    - "do_not_call"
    - "channel_pref"
    - "age"
    - "last_flu_shot_date"
  joins:
  - name: "member-flu-risk"
    join:
      primarySourceColumn: "member_id"
      joinSourceColumn: "member_id"
      joinType: "left"
    profileGroup: "Inferences"
    timestamp:
      auto: false
      field: "date"
      format: "yyyy-MM-dd"
      fixed: null
    attributes:
    - "flu_risk_score"
  attributes:
  - type: "custom"
    name: "avg_flu_risk"
    profileGroup: "Inferences"
    source:
      name: "member-flu-risk"
    expression: "flu_risk_score.mean()"
    window: "DAILY"
  - type: "custom"
    name: "flu_risk_1_pct"
    profileGroup: "Inferences"
    source:
      name: "member-flu-risk"
    expression: "flu_risk_score.percentile(0.99)"
    window: "DAILY"
  - type: "custom"
    name: "is_flu_risk_1_pct"
    profileGroup: "Inferences"
    source:
      name: ""
    expression: "flu_risk_score.gte(flu_risk_1_pct)"
    window: null
  - type: "custom"
    name: "has_phone_number"
    profileGroup: "Demographics"
    source:
      name: "member-base"
    expression: "phone.notEqual('').or(phone.notEqual(null))"
    window: null
  - type: "bucket"
    name: "age_group"
    profileGroup: "Demographics"
    source:
      name: "member-base"
    buckets:
    - name: "Under 30"
      filter: "age.lt(30)"
    - name: "30-45"
      filter: "age.gte(30).and(age.lt(45))"
    - name: "45-55"
      filter: "age.gte(45).and(age.lt(55))"
    - name: "55-65"
      filter: "age.gte(55).and(age.lt(65))"
    - name: "65+"
      filter: "age.gte(65)"
  attributeTags: []
  title: "member-profile"
  description: null