---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-base-file"
spec:
  title: Member Base File
  connectionType: file
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: ./src/main/resources/data/members_100_v14.csv
    - name: csv/header
      value: true
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-feedback-file"
spec:
  title: Member Feedback File
  connectionType: file
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: ./src/main/resources/data/feedback_100_v14.csv
    - name: csv/header
      value: true
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-flu-risk-file"
spec:
  title: Member Flu File
  connectionType: file
  contentType: parquet
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: ./src/main/resources/data/member_flu_risk_100_v14.parquet
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "member-joined-file"
spec:
  title: Member Joined File
  connectionType: file
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
    - name: csv/header
      value: true
    - name: uri
      value: ./build/tmp/test-data/joined_v14.csv
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "cdata-csv"
spec:
  title: CDATA CSV
  connectionType: jdbc
  params:
    - name: query
      value: select * from members_100_v14
    - name: url
      value: jdbc:csv:GenerateSchemaFiles=OnStart;URI=file://./src/main/resources/data/members_100_v14.csv;Location=./build/tmp;
    - name: driver
      value: cdata.jdbc.csv.CSVDriver
    - name: oem_key
      value: '#SECURE.oem_key'
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "cdata-bigquery"
spec:
  title: CDATA BigQuery
  connectionType: jdbc
  params:
    - name: query
      value: SELECT * FROM `bigquery-public-data.covid19_weathersource_com.postal_code_day_forecast` WHERE forecast_date = '2022-06-03' LIMIT 10
    - name: url
      value: jdbc:cdata:googlebigquery:AuthScheme:OAuthJWT;InitiateOAuth=GETANDREFRESH;OAuthJWTCertType:GOOGLEJSON;OAuthJWTCert:/secure-storage/gcp-service-account.json;ProjectId=fabric-qa;DatasetId=covid19_weathersource_co;
    - name: driver
      value: cdata.jdbc.googlebigquery.GoogleBigQueryDriver
    - name: oem_key
      value: '#SECURE.oem_key'
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "bigquery"
spec:
  title: BigQuery Spark Connector
  connectionType: gcs #bigquery
  params:
    #    - name: query
    #      value: SELECT * FROM bigquery-public-data.samples.shakespeare
    #    - name: project
    #      value: fabric-qa
    - name: parentProject
      value: fabric-qa
    - name: table
      value: bigquery-public-data.samples.shakespeare
    - name: credentialsFile
      value: /secure-storage/gcp-service-account.json
    - name: format
      value: bigquery
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "sink"
spec:
  title: Sink File
  connectionType: file
  contentType: parquet
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: file:///opt/spark/work-dir/build/tmp/test-data/sink-ds/
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: member-base-s3-stream
spec:
  title: Member Base S3 File
  connectionType: s3FileStream
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
    - name: uri
      value: s3a://cortex-examples/data/data-streaming/members_100_v14.csv
    - name: publicKey
      value: csuser
    - name: secretKey
      value: cortexfabric
    - name: s3Endpoint
      value: http://localhost:9000
    - name: sslEnabled
      value: false
    - name: pathStyleAccess
      value: true
    - name: csv/header
      value: true
    - name: stream_read_dir
      value: s3a://cortex-examples/data/data-streaming
    - name: isTriggered
      value: false
    - name: pollInterval
      value: 10
    - name: csv/multiline
      value: true
    - name: csv/header
      value: true
