---
apiVersion: cognitivescale.io/v1
kind: DataSource
metadata:
  name: member-base-ds
spec:
  kind: batch
  primaryKey: member_id
  connection:
    name: member-base-file
  attributes:
    - member_id
    - state_code
    - city
    - state
    - zip_code
    - gender
    - segment
    - member_health_plan
    - is_PCP_auto_assigned
    - pcp_tax_id
    - phone
    - do_not_call
    - channel_pref
    - age
    - last_flu_shot_date
    - pcp_name
