# Singleton service factory configuration/IoC injection
singletons:
# Startup Hook Implementation
- com.networknt.server.StartupHookProvider:
  - com.c12e.cortex5.provider.CortexSystemEventHandler
- com.networknt.server.ShutdownHookProvider:
  - com.c12e.cortex5.provider.CortexSystemEventHandler
# HandlerProvider implementation
- com.networknt.handler.HandlerProvider:
  - com.c12e.cortex5.provider.CortexSystemEventHandler
- com.networknt.handler.MiddlewareHandler:
# Exception Global exception handler that needs to be called first to wrap all middleware handlers and business handlers
  - com.networknt.exception.ExceptionHandler
#  Body Parse body based on content type in the header.
  - com.networknt.body.BodyHandler
# SimpleAudit Logger
  - com.networknt.audit.AuditHandler
#  - javax.sql.DataSource:
#    - com.zaxxer.hikari.HikariDataSource:
#        DriverClassName: org.apache.hive.jdbc.HiveDriver
#        jdbcUrl: jdbc:hive2://127.0.0.1:10000/default
#        username:
#        password:
#  Cors Handler
#  - com.networknt.cors.CorsHttpHandler
#
#
#  # Metrics handler to calculate response time accurately, this needs to be the second handler in the chain.
#  - com.networknt.metrics.MetricsHandler
#  # Traceability Put traceabilityId into response header from request header if it exists
#  - com.networknt.traceability.TraceabilityHandler
#  # SimpleAudit Log important info about the request into audit log
#  - com.networknt.audit.AuditHandler
#  # Sanitizer Encode cross site scripting
#  - com.networknt.sanitizer.SanitizerHandler